"""empty message

Revision ID: f4a033cbdcc4
Revises: 7499b539bf48
Create Date: 2020-01-12 21:49:56.680023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4a033cbdcc4'
down_revision = '7499b539bf48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=150), nullable=False))
    op.drop_column('user', 'avengername')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avengername', sa.VARCHAR(length=150), nullable=False))
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
